example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [path('', show_katalog, name='show_katalog'),]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_xml, show_json,\
    show_xml_by_id, show_json_by_id, show_html

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/', show_html, name='show_html'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import delete_task, show_todolist, register, login_user,\
    logout_user, create_task, delete_task, update_task, get_todolist_json, add_task_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('delete-task/<id>/', delete_task, name='delete_task'),
    path('update-task/<id>/', update_task, name='update_task'),
    path('json/', get_todolist_json, name='get_todolist_json'),
    path('add/', add_task_ajax, name='add_task_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.

class MovieWatchlist(models.Model):
    watched = models.CharField(max_length=225)
    title = models.CharField(max_length=225)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=225)
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    catalog_item_data = CatalogItem.objects.all()
    context = {
        'list_item': catalog_item_data,
        'nama': 'TM Revanza Narendra Pradipta',
        'npm': '2206025003',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MovieWatchlist
from mywatchlist.message import return_message
from django.http import HttpResponse
from django.core import serializers

def returnData():
    return MovieWatchlist.objects

# Create your views here.
def show_watchlist(request):
    data_movie_watchlist = returnData().all()
    context = {
        'list_movie': data_movie_watchlist,
        'nama': 'Tm Revanza Narendra Pradipta',
        'npm': '2206025003',
        'message': return_message, # Mengembalikan pesan sesuai dengan jumlah film yang sudah ditonton
    }
    return render(request, "watchlist.html", context)

def show_html(request):
    return show_watchlist(request)

def show_xml(request):
    data = returnData().all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_xml_by_id(request, id):
    data = returnData().filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = returnData().all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = returnData().filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from todolist.models import Task
from todolist.forms import TaskForm

# Create your views here.
@login_required(login_url='/todolist/login/')
@csrf_exempt
def show_todolist(request):
    data = Task.objects.filter(user=request.user)

    context = {
        'task':data,
        'username':request.user,
    }
    return render(request, 'todolist.html', context)

def create_task(request):
    form = TaskForm()
    
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('todolist:show_todolist')

    return render(request, 'create_task.html', {'form':form})

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

# Tugas 6
def get_todolist_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def add_task_ajax(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_task = Task(title=title, description=description, user=request.user)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def update_task(request, id):
    if request.method == "POST":
        task = Task.objects.filter(pk=id, user=request.user).first()
        task.is_finished = not task.is_finished
        task.save()
        
        return HttpResponse(b"UPDATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def delete_task(request, id):
    if request.method == "DELETE":
        task = Task.objects.filter(pk=id, user=request.user).first()
        task.delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/index.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Fill me!</p>

  <h5>Student ID: </h5>
  <p>Fill me!</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
  </table>

 {% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
      <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.description}}</th>
        <th>{{item.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 2 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <p style="color:blue;font-size:25px";><b>{{message}}</b></p>

  <table>
    <tr style="font-size:20px">
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for movie in list_movie %}
      <tr>
        <th>{{movie.watched}}</th>
        <th>{{movie.title}}</th>
        <th>{{movie.rating}}</th>
        <th>{{movie.release_date}}</th>
        <th>{{movie.review}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Create Task</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <style>
            body {
                text-align: center;
                background-color: rgb(26, 22, 22);
            } 

            form {
                width: 100%;
                padding-left: 25px;
                padding-right: 25px;
                padding-top: 20px;
                padding-bottom: 20px;
                background-color: rgb(59, 54, 54);
                box-shadow: 0 0 15px rgb(59, 54, 54);
                display: inline-block;
                border: 0px solid;
                margin: 10px;
                text-align: center;
                border-color: rgb(97, 95, 95);
                border-radius: 12px;
            }

            .create-task {
                display: inline-block;
            }

            font {
                color: white;
            }

            a {
                color:black; 
                text-decoration: none;
            }  
        </style>
    </head>

    <body>
        <h1 style="margin-top: 25px"><font>Create New Task</font></h1>

        <div class="container">
            <div class = "create-task mt-3">
                <form method="POST" action="">
                    {% csrf_token %} 
                    <table>
                        <tr>
                            <td><p style="text-align: left"><font>Title:</font></p></td>
                        </tr>
                        <tr>
                            <td><input type="text" name="title" class="form-control mb-2"></td>
                        </tr>
                        
                        <tr>
                            <td><p style="text-align: left"><font>Description:</font></p></td>
                        </tr>

                        <tr>
                            <td><textarea name="description" class="form-control" style="height:200px; width:100%"></textarea></td>
                        </tr>
                        <tr>  
                            <td><input class="btn btn-primary btn-sm mt-3" type="submit" name="submit" value="Submit" style="color: white; width: 100%;"></td>  
                        </tr>
                    </table>
                </form>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

todolist/templates/login.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <style>
            body {
                text-align: center;
                background-color: rgb(26, 22, 22);
            }
            
            form {
                padding-left: 20px;
                padding-right: 20px;
                padding-top: 20px;
                padding-bottom: 20px;
                background-color: rgb(59, 54, 54);
                box-shadow: 0 0 15px rgb(59, 54, 54);
                display: inline-block;
                border:0px solid;
                margin: 10px;
                text-align: center;
                border-color: rgb(97, 95, 95);
                border-radius: 12px;
            }
            .login {
                display: inline-block;
            }
        </style>
    </head>

    <body>
        <div class="container">
            <div class = "login mt-3">

                <h1 style="color: white;">LOGIN</h1>
            
                <form method="POST" action="">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td><input type="text" name="username" placeholder="Username" class="form-control mt-1"></td>
                        </tr>

                        <tr>
                            <td><input type="password" name="password" placeholder="Password" class="form-control mt-3"></td>
                        </tr>
            
                        <tr>
                            <td><input class="btn btn-primary btn-sm mt-3" type="submit" value="Login" style="color: white; width: 100%;"></td>
                        </tr>
                    </table>
                </form>
            
            
                <p></p>
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li style="color:white;">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}     
                    
                <font style="color:white">Don't have an account yet?</font> <a href="{% url 'todolist:register' %}">Register now</a>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

todolist/templates/register.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Registrasi Akun</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <style>
            body {
                text-align: center;
                background-color: rgb(26, 22, 22);
            }
            
            form {
                padding-left: 20px;
                padding-right: 20px;
                padding-top: 20px;
                padding-bottom: 20px;
                background-color: rgb(59, 54, 54);
                box-shadow: 0 0 15px rgb(59, 54, 54);
                display: inline-block;
                border:0px solid;
                margin: 10px;
                text-align: center;
                border-color: rgb(97, 95, 95);
                border-radius: 12px;
            }
            .login {
                display: inline-block;
            }
            
            font {
                color: white;
            }
        </style>
    </head>

    <body>
        <div class="container">
            <div class = "login mt-3">
        
                <h1><font>Formulir Registrasi</font></h1>  
        
                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        <tr>
                            <td><p style="text-align: left"><font>Username:</font></p></td>
                        </tr>
                        <tr>
                            <td><input type="text" name="username" class="form-control mb-3" required/></td>
                        </tr>
                        
                        <tr>
                            <td><p style="text-align: left"><font>Password:</font></p></td>
                        </tr> 

                        <tr>
                            <td><input type="password" name="password1" class="form-control mb-3" required/></td>
                        </tr>

                        <tr>
                            <td><p style="text-align: left"><font>Password Confirmation:</font></p></td>
                        </tr>

                        <tr>
                            <td><input type="password" name="password2" class="form-control" required/></td>
                        </tr>

                        <tr>  
                            <td><input class="btn btn-primary btn-sm mt-3" type="submit" name="submit" value="Daftar" style="color: white; width: 100%"/></td>  
                        </tr>  

                    </table>  
                </form>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

todolist/templates/todolist.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task 5</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <style>
      body {
        background-color: rgb(26, 22, 22);
      }
      .card {
        width: 13rem;
        background-color: rgb(102, 88, 158);
        box-shadow: 0 0  8px rgb(72, 58, 58);
      }
      .card:hover {
        box-shadow: 0 0 8px rgb(99, 85, 85);
        transform: translateY(-3px);
      }
      a {
        color:black; 
        text-decoration: none;
      }
      button {
        border: none;
        border-radius: 4px;
      }
      button:hover {
        box-shadow: 0 0 4px rgb(72, 58, 58);
      }
      button:active {
        transform: translateY(-2px);
      }
      .btn {
        border: none;
        margin-top: auto;
      }
      .checklist-btn {
        background: none;
        margin-top: auto;
      }
      .delete-btn {
        background-color: rgb(197, 38, 38);
        margin-top: auto;
      }
      #create-btn {
        background-color: rgb(102, 88, 158);
      }
      font {
        color: white;
      }
      .modal-content {
        background-color: rgb(59, 54, 54);
      }
      .close {
        background: none;
        color: white;
      }
      
    </style>
  </head>

  <body>
    {% csrf_token %} 
    <nav class="navbar navbar-dark" style="background-color:rgb(36, 33, 39); ">
      <div class="container-fluid">
          <a class="navbar-brand" href="#" style="color:rgb(151, 136, 209)">Task 5 Assignment PBP/PBD</a>
          <button class="btn btn-outline-light" type="button"><a href="{% url 'todolist:logout' %}" style="color:rgb(197, 38, 38)">logout</a></button>
      </div>
    </nav>
  
    <div class="container">
      <div class="title" style="padding-top: 7px; padding-left: 7px; padding-right: 7px;">
        <h6><font>Welcome, {{username}}</font></h6>
        <h3><font>List of Tasks</font></h3>
        <button id="create-btn" data-bs-toggle="modal" data-bs-target="#createTaskModal"><font>Add Task</font></button>
      </div>
    </div>

    <div class="container">
      <div class="row mt-1" id="cardPlace" style="padding-top: 1px; padding-left: 7px; padding-right:7px; padding-bottom: 7px;"></div>
    </div>

    <div class="modal fade" id="createTaskModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header border-0">
            <h5 class="modal-title"><font>CREATE NEW TASK</font></h5>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form id="createTaskForm" onsubmit="return false;">
            {% csrf_token %}
            <div class="modal-body">
              <fieldset>
                  <input type="text" name="title" placeholder="Title" class="form-control mb-2">
                  <textarea name="description" class="form-control" placeholder="Description" style="height:200px; width:100%"></textarea>
              </fieldset>
            </div>
            <div class="modal-footer border-0">
              <button id="btn-submit" class="btn btn-primary" value="Submit" type="submit" data-bs-dismiss="modal">Submit</button>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>

  <script>
    async function getTodolist() {
      return fetch("{% url 'todolist:get_todolist_json' %}").then((res) => res.json())
    }

    async function refreshTodolist() {
      document.getElementById("createTaskForm").reset();
      const todolistData = await getTodolist()
      let htmlString = ``
      todolistData.forEach((item) => {
        var fields = item.fields
        var divCol = document.createElement("div");
        divCol.classList.add("col-md-3");
        divCol.style.cssText += 'padding-top: 15px;';

        var divCard = document.createElement("div");
        divCard.classList.add("card");
        divCard.classList.add("h-100");
        if (fields.is_finished) {
          divCard.style.cssText += 'background-color: rgb(34, 188, 60);';
        } else {
          divCard.style.cssText += '';
        }

        var divCardBody = document.createElement("div");
        divCardBody.classList.add("card-body");
        divCardBody.classList.add("d-flex");
        divCardBody.classList.add("flex-column");

        var cardTitle = document.createElement("h5");
        cardTitle.classList.add("card-title");
        cardTitle.classList.add("text-white");
        cardTitle.innerHTML = fields.title
        divCardBody.appendChild(cardTitle);

        var cardDate = document.createElement("h6");
        cardDate.classList.add("card-text");
        cardDate.classList.add("text-white");
        cardDate.innerHTML = fields.date
        divCardBody.appendChild(cardDate);

        var cardDesc = document.createElement("p");
        cardDesc.classList.add("card-text");
        cardDesc.classList.add("text-white");
        cardDesc.innerHTML = fields.description
        divCardBody.appendChild(cardDesc);

        var divBtn = document.createElement("div");
        divBtn.classList.add("btn");

        var checklistBtn = document.createElement("button");
        checklistBtn.classList.add("checklist-btn");
        checklistBtn.classList.add("text-white");
        checklistBtn.innerHTML = "Checklist";
        checklistBtn.setAttribute('onclick', `updateTask(${item.pk})`);
        divBtn.appendChild(checklistBtn);

        var deleteBtn = document.createElement("button");
        deleteBtn.classList.add("delete-btn");
        deleteBtn.classList.add("text-white");
        deleteBtn.innerHTML = "Delete";
        deleteBtn.setAttribute('onclick', `deleteTask(${item.pk})`);
        divBtn.appendChild(deleteBtn);

        divCardBody.appendChild(divBtn);
        divCard.appendChild(divCardBody);
        divCol.appendChild(divCard);

        htmlString += divCol.outerHTML
      });

      document.getElementById("cardPlace").innerHTML = htmlString;
    }

    function updateTodolist() {
      $.getJSON("{% url 'todolist:get_todolist_json' %}", refreshTodolist);
    }

    function updateTask(pk) {
      $.ajax({
        url:`update-task/${pk}/`,
        type: 'POST',
        success: updateTodolist,
      });
    }

    function deleteTask(pk) {
      $.ajax({
        url:`delete-task/${pk}/`,
        type: 'DELETE',
        success: updateTodolist,
      });
    }

    function addTask() {
      fetch("{% url 'todolist:add_task_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#createTaskForm'))
      }).then(refreshTodolist)
      return false
    }
    
    document.getElementById("btn-submit").onclick = addTask
    refreshTodolist()
  </script>
</html>